version: '3'

services:
  postgres:
    image: postgres:12
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=chatwoot
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - chatwoot

  redis:
    image: redis:alpine
    restart: always
    command: ["sh", "-c", "redis-server --requirepass \"$REDIS_PASSWORD\""]
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    networks:
      - chatwoot

  chatwoot:
    image: chatwoot/chatwoot:latest
    restart: always
    depends_on:
      - postgres
      - redis
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_NAME=GlowDance Support

      # Database
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=chatwoot
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

      # Redis
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379

      # Application
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - FRONTEND_URL=${FRONTEND_URL}
      - FORCE_SSL=false

      # Email (SMTP)
      - MAILER_SENDER_EMAIL=${MAILER_SENDER_EMAIL}
      - SMTP_ADDRESS=${SMTP_ADDRESS}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_AUTHENTICATION=plain
      - SMTP_ENABLE_STARTTLS_AUTO=true
      - SMTP_OPENSSL_VERIFY_MODE=none

      # Email (IMAP - for receiving replies)
      - IMAP_ADDRESS=${IMAP_ADDRESS}
      - IMAP_PORT=${IMAP_PORT}
      - IMAP_EMAIL=${IMAP_EMAIL}
      - IMAP_PASSWORD=${IMAP_PASSWORD}
      - IMAP_ENABLE_SSL=true

      # Storage (Local for now, can switch to S3 later)
      - ACTIVE_STORAGE_SERVICE=local

      # Optional: Enable if you need
      # - ENABLE_ACCOUNT_SIGNUP=false
      # - USE_INBOX_AVATAR_FOR_BOT=true

    volumes:
      - chatwoot_data:/app/storage
    networks:
      - chatwoot
    entrypoint: docker/entrypoints/rails.sh
    command: ['bundle', 'exec', 'rails', 's', '-p', '3000', '-b', '0.0.0.0']

  sidekiq:
    image: chatwoot/chatwoot:latest
    restart: always
    depends_on:
      - postgres
      - redis
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_NAME=GlowDance Support

      # Database
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=chatwoot
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

      # Redis
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379

      # Application
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - FRONTEND_URL=${FRONTEND_URL}

      # Email
      - MAILER_SENDER_EMAIL=${MAILER_SENDER_EMAIL}
      - SMTP_ADDRESS=${SMTP_ADDRESS}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_AUTHENTICATION=plain
      - SMTP_ENABLE_STARTTLS_AUTO=true

      # Storage
      - ACTIVE_STORAGE_SERVICE=local

    volumes:
      - chatwoot_data:/app/storage
    networks:
      - chatwoot
    command: ['bundle', 'exec', 'sidekiq', '-C', 'config/sidekiq.yml']

volumes:
  postgres_data:
  redis_data:
  chatwoot_data:

networks:
  chatwoot:
    driver: bridge
